

name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-nightly-only:
    name: Build nightly only
    runs-on: ubuntu-latest
    container: saferq/wrap-rocks:0.2.0
    steps:
      - uses: actions/checkout@v1
        #- name: Install  rust
        #run: curl --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      # Insert steps here to install you other dependencies. Note that you're running inside of cent os 7, not ubuntu
      #- name: Installing custom dependency
      #  run: echo "Installing yum plugins"
      - name: Build
        run: |
          #source $HOME/.cargo/env
          for PYBIN in /opt/python/cp3[891]*/bin; do
          #"${PYBIN}/pip" install maturin cffi
            "${PYBIN}/python" -m maturin build -m Cargo.toml -i "${PYBIN}/python" --release # --manylinux 2014
          done
      # Auditwheel isn't generally necessary. This is only shown as refernce for cases where you link
      # external libraries, in which case you have to set manylinux to off and then use auditwheel repair
      - name: Auditwheel repair
        run: |
          for wheel in nightly-only/target/wheels/*.whl; do
              auditwheel repair "${wheel}"
          done
