

name: Build wrap-rocks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build wheels
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    container: saferq/wrap-rocks:latest
    steps:
      - uses: actions/checkout@v2
      - name: build-wheels
        run: |
          source /usr/local/cargo/env
          python${{ matrix.python-version }} -m maturin build -m Cargo.toml -i python${{ matrix.python-version }} --release
      
      - name: auditwheels
        run: |
          for wheel in target/wheels/*.whl; do
            auditwheel repair "${wheel}"
            python3.12 -m maturin upload ${wheel} -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
            done
  
